# Site settings
title: "David Patiño"
email: "davida.psicologia@gmail.com"
url: "https://psico-logia.github.io"
description: "Psico.logia Contactame a traves de esta pag" 
keywords: "psico.logia, psicologia, psicología, david patiño, david psicologo"
skills: "Psicólogo - Experto en terapias de tercera generación"
meta_author: "Patiño David"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0808C4 #0808C4
  primary-rgb: "8,8,196" #"8,8,196"
  secondary: 1B1B6F #1B1B6F
  secondary-dark: 0B0B46 #A2122F

# Footer settings
footer:
  copyright: Psico.logia
  location: 
  social: Sigueme en mis redes sociales 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/psico.logia.co/
  - title: tiktok
    url: https://www.tiktok.com/@psico.logia
  - title: whatsapp
    url: https://wa.me/message/DTLMV4VSDUUJI1
  - title: linkedin
    url: https://www.linkedin.com/in/david-psico-logia/
 # - title: 
 #   url: 

# Postal address (add as many lines as necessary)
#address:
# - line: 3481 Melrose Place
#- line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
